version: '3.9'
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    networks:
      - infrastructure
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ddclient:/config
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.platform==linux"
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
    logging:
      options:
        loki-external-labels: "job=ddclient"

volumes:
  ddclient:
    name: ddclient
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.19,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/share/docker/ddclient"

networks:
  infrastructure:
    name: infrastructure
    external: true